<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['cipher_result'] = array(
        'title' => 'Cipher Results',
        'page callback' => 'cipher_result_display',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => t('Enter the amount you would like the text shifted'),
    );

    $form['direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Enter the direction to shift the text (left or right)'),
    );

    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Enter the phrase you would like to be encrypted'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );

    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    if ($direction === 'left') {
        $shift_value = 26 - $shift_value;
    }
    $phrase = $form_state['values']['phrase'];

    $plain_array = str_split($phrase);
    $encrypted_array = array();
    foreach ($plain_array as $character) {
        $ascii_val = ord($character);
        if ($ascii_val >= 65 && $ascii_val <= 90) {
            $new_ascii = $ascii_val + $shift_value;
            if ($new_ascii > 90) {
                $new_ascii = $new_ascii % 91 + 65;
            }
            $encrypted_array[] = chr($new_ascii);
        } elseif ($ascii_val >= 97 && $ascii_val <= 122) {
            $new_ascii = $ascii_val + $shift_value;
            if ($new_ascii > 122) {
                $new_ascii = $new_ascii % 123 + 97;
            }
            $encrypted_array[] = chr($new_ascii);
        } else {
            $encrypted_array[] = chr($ascii_val);
        }
    }

    $_SESSION['encrypted_phrase'] = implode($encrypted_array);
    $form_state['redirect'] = 'cipher_result';
}

function cipher_result_display() {
    return $_SESSION['encrypted_phrase'];
}
